#!/usr/bin/env python3
"""
Pixelator Grid: A tool to extract and recreate pixel art from images with detected grid.

This script uses the grid_detector module to find the pixel grid, calculates
the average color of each grid cell, and creates both 1:1 and scaled versions
of the pixel art representation.
"""

import os
import argparse
import numpy as np
from PIL import Image
import grid_detector
from sklearn.cluster import KMeans


def read_grid_coordinates(grid_coords_path):
    """
    Read grid coordinates from a file generated by grid_detector.py.

    Args:
        grid_coords_path: Path to the grid coordinates file

    Returns:
        Tuple of (row_edges, col_edges) arrays
    """
    row_edges = []
    col_edges = []
    current_section = None

    with open(grid_coords_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                if "Row positions" in line:
                    current_section = "rows"
                elif "Column positions" in line:
                    current_section = "cols"
                continue

            try:
                position = int(line)
                if current_section == "rows":
                    row_edges.append(position)
                elif current_section == "cols":
                    col_edges.append(position)
            except ValueError:
                pass

    return np.array(row_edges), np.array(col_edges)


def calculate_average_colors(image_array, row_edges, col_edges, max_colors=None):
    """
    Calculate the average color for each grid cell, with optional color palette limitation.

    Args:
        image_array: Original image as numpy array
        row_edges: Array of row edge positions
        col_edges: Array of column edge positions
        max_colors: Maximum number of colors in the palette (if None, no limitation)

    Returns:
        2D array of average RGB colors for each grid cell
    """
    # Add image boundaries to edges if they're not already included
    height, width, _ = image_array.shape

    # Ensure we have the first and last positions
    if 0 not in row_edges:
        row_edges = np.concatenate([[0], row_edges])
    if height not in row_edges:
        row_edges = np.concatenate([row_edges, [height]])

    if 0 not in col_edges:
        col_edges = np.concatenate([[0], col_edges])
    if width not in col_edges:
        col_edges = np.concatenate([col_edges, [width]])

    # Sort edges to ensure they're in ascending order
    row_edges.sort()
    col_edges.sort()

    # Calculate grid dimensions
    grid_height = len(row_edges) - 1
    grid_width = len(col_edges) - 1

    # Initialize result array
    avg_colors = np.zeros((grid_height, grid_width, 3), dtype=np.uint8)

    # Calculate average color for each grid cell
    for i in range(grid_height):
        row_start = row_edges[i]
        row_end = row_edges[i + 1]

        for j in range(grid_width):
            col_start = col_edges[j]
            col_end = col_edges[j + 1]

            # Extract the grid cell and calculate average color
            cell = image_array[row_start:row_end, col_start:col_end]
            if cell.size > 0:  # Make sure the cell is not empty
                avg_color = np.mean(cell, axis=(0, 1)).astype(np.uint8)
                avg_colors[i, j] = avg_color
    
    # Apply color quantization if max_colors is specified
    if max_colors is not None and max_colors > 0:
        # Reshape the colors to a list
        pixels = avg_colors.reshape(-1, 3)
        
        # Use k-means clustering to find the dominant colors
        kmeans = KMeans(n_clusters=max_colors, random_state=42, n_init=10)
        kmeans.fit(pixels)
        
        # Get the colors from the cluster centers
        colors = kmeans.cluster_centers_.astype(np.uint8)
        
        # Map each pixel to its nearest cluster center
        labels = kmeans.predict(pixels)
        quantized = colors[labels]
        
        # Reshape back to the original grid dimensions
        avg_colors = quantized.reshape(grid_height, grid_width, 3)

    return avg_colors


def create_scaled_image(pixel_array, scale_factor=None):
    """
    Create a scaled version of the pixel art, where each pixel is represented
    by an NxN square of the same color.

    Args:
        pixel_array: 2D array of RGB colors for each grid cell
        scale_factor: Factor to scale each pixel (default: auto-calculate)

    Returns:
        Scaled pixel art image as numpy array
    """
    grid_height, grid_width, _ = pixel_array.shape

    # Determine scaling factor to maintain proportions
    if scale_factor is None:
        # Auto-calculate a scale factor that results in a reasonable output size
        target_width = 800  # Reasonable target width
        scale_factor = max(1, target_width // grid_width)

    # Create scaled image
    scaled_height = grid_height * scale_factor
    scaled_width = grid_width * scale_factor
    scaled_image = np.zeros((scaled_height, scaled_width, 3), dtype=np.uint8)

    # Fill each pixel with its color
    for i in range(grid_height):
        for j in range(grid_width):
            y_start = i * scale_factor
            y_end = (i + 1) * scale_factor
            x_start = j * scale_factor
            x_end = (j + 1) * scale_factor

            scaled_image[y_start:y_end, x_start:x_end] = pixel_array[i, j]

    return scaled_image


def create_comparison_image(original_image, pixel_array, row_edges, col_edges):
    """
    Create a side-by-side comparison of the original image and the detected pixels.

    Args:
        original_image: Original image as numpy array
        pixel_array: 2D array of average RGB colors for each grid cell
        row_edges: Array of row edge positions
        col_edges: Array of column edge positions

    Returns:
        Comparison image as numpy array
    """
    height, width, _ = original_image.shape

    # Create a pixelated version of the original image
    pixelated = np.copy(original_image)

    # Fill each pixel with its average color
    for i in range(len(row_edges) - 1):
        row_start = row_edges[i]
        row_end = row_edges[i + 1]

        for j in range(len(col_edges) - 1):
            col_start = col_edges[j]
            col_end = col_edges[j + 1]

            # Fill the region with the average color
            pixelated[row_start:row_end, col_start:col_end] = pixel_array[i, j]

    # Create a side-by-side comparison
    comparison = np.zeros((height, width * 2, 3), dtype=np.uint8)
    comparison[:, :width] = original_image
    comparison[:, width:] = pixelated

    # Add a vertical white line separator
    comparison[:, width - 1 : width + 1] = [255, 255, 255]

    return comparison


def process_image(
    image_path,
    grid_coords_path=None,
    output_dir=None,
    scale_factor=None,
    auto_detect=True,
    row_spacing=None,
    col_spacing=None,
    window_size=2,
    row_threshold=90,
    col_threshold=90,
    algorithm="euclidean",
    max_colors=None,
):
    """
    Process an image to create pixelated versions.

    Args:
        image_path: Path to the input image
        grid_coords_path: Path to grid coordinates file (if None, will be derived from image_path)
        output_dir: Directory to save outputs (default: same as input)
        scale_factor: Factor to scale each pixel in the scaled output (default: auto-calculate)
        auto_detect: Whether to run grid detection if grid_coords_path doesn't exist

    Returns:
        Dictionary with paths to the output files
    """
    # Default output directory is the same as input directory
    if output_dir is None:
        output_dir = os.path.dirname(image_path)
        if output_dir == "":
            output_dir = "."

    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Base filename for outputs
    base_filename = os.path.splitext(os.path.basename(image_path))[0]

    # Derive grid coordinates path if not provided
    if grid_coords_path is None:
        grid_coords_path = f"{output_dir}/{base_filename}_grid_coords.txt"

    # Run grid detection if needed
    # Always regenerate grid if row_spacing or col_spacing is specified
    force_regenerate = row_spacing is not None or col_spacing is not None
    if (auto_detect and not os.path.exists(grid_coords_path)) or force_regenerate:
        print("Grid coordinates not found, running grid detection...")
        grid_result = grid_detector.detect_grid(
            image_path,
            output_dir=output_dir,
            row_approx_spacing=row_spacing,
            col_approx_spacing=col_spacing,
            window_size=window_size,
            row_threshold=row_threshold,
            col_threshold=col_threshold,
            algorithm=algorithm,
        )
        grid_coords_path = grid_result["grid_coords"]

    # Check if grid coordinates exist
    if not os.path.exists(grid_coords_path):
        raise FileNotFoundError(f"Grid coordinates file not found: {grid_coords_path}")

    # Load the original image
    image_array = grid_detector.edge_detector.load_image(image_path)
    print(f"Loaded image with shape {image_array.shape}")

    # Read grid coordinates
    row_edges, col_edges = read_grid_coordinates(grid_coords_path)
    print(f"Read grid with {len(row_edges)} rows and {len(col_edges)} columns")

    # Calculate average colors for each grid cell
    avg_colors = calculate_average_colors(image_array, row_edges, col_edges, max_colors)
    print(
        f"Calculated average colors for {avg_colors.shape[0]}x{avg_colors.shape[1]} grid cells"
    )
    if max_colors is not None:
        print(f"Applied color quantization to limit palette to {max_colors} colors")

    # Save the 1:1 pixel art (one pixel per grid cell)
    one_to_one_path = f"{output_dir}/{base_filename}_1x1_pixels.png"
    Image.fromarray(avg_colors).save(one_to_one_path)
    print(f"Saved 1:1 pixel art to {one_to_one_path}")

    # Create scaled version
    scaled = create_scaled_image(avg_colors, scale_factor)
    scaled_path = f"{output_dir}/{base_filename}_scaled_pixels.png"
    Image.fromarray(scaled).save(scaled_path)
    print(f"Saved scaled pixel art to {scaled_path}")

    # Create comparison image
    comparison = create_comparison_image(image_array, avg_colors, row_edges, col_edges)
    comparison_path = f"{output_dir}/{base_filename}_comparison.png"
    Image.fromarray(comparison).save(comparison_path)
    print(f"Saved comparison image to {comparison_path}")

    return {
        "one_to_one": one_to_one_path,
        "scaled": scaled_path,
        "comparison": comparison_path,
    }


def main():
    """Parse command line arguments and run the pixelation process."""
    parser = argparse.ArgumentParser(
        description="Create pixelated versions of images using detected grid"
    )
    parser.add_argument("input", help="Path to the input image")
    parser.add_argument("-g", "--grid-coords", help="Path to grid coordinates file")
    parser.add_argument("-o", "--output-dir", help="Directory to save outputs")
    parser.add_argument(
        "-s", "--scale", type=int, help="Scale factor for pixels in the output image"
    )
    parser.add_argument(
        "--no-auto-detect",
        action="store_true",
        help="Disable automatic grid detection if grid coordinates file doesn't exist",
    )

    # Grid detection parameters
    parser.add_argument(
        "--spacing",
        type=int,
        help="Approximate spacing between pixels (sets both row and column spacing)"
    )
    parser.add_argument(
        "--row-spacing", type=int, help="Approximate spacing between rows (pixels)"
    )
    parser.add_argument(
        "--col-spacing", type=int, help="Approximate spacing between columns (pixels)"
    )
    parser.add_argument(
        "-w",
        "--window",
        type=int,
        default=2,
        help="Size of the search window around expected positions",
    )
    parser.add_argument(
        "--row-threshold",
        type=int,
        default=90,
        help="Percentile threshold for row edge detection (0-100)",
    )
    parser.add_argument(
        "--col-threshold",
        type=int,
        default=90,
        help="Percentile threshold for column edge detection (0-100)",
    )
    parser.add_argument(
        "-m",
        "--algorithm",
        choices=["absolute", "squared", "euclidean", "max"],
        default="euclidean",
        help="Algorithm for calculating differences",
    )
    parser.add_argument(
        "-c",
        "--colors",
        type=int,
        help="Maximum number of colors in the palette (default: no limit)",
    )

    args = parser.parse_args()

    # Process the image
    # If spacing is specified, use it for both row and column spacing
    row_spacing = args.spacing if args.spacing is not None else args.row_spacing
    col_spacing = args.spacing if args.spacing is not None else args.col_spacing
    
    outputs = process_image(
        args.input,
        grid_coords_path=args.grid_coords,
        output_dir=args.output_dir,
        scale_factor=args.scale,
        auto_detect=not args.no_auto_detect,
        row_spacing=row_spacing,
        col_spacing=col_spacing,
        window_size=args.window,
        row_threshold=args.row_threshold,
        col_threshold=args.col_threshold,
        algorithm=args.algorithm,
        max_colors=args.colors,
    )

    print("\nSummary:")
    print(f"  Input image: {args.input}")
    print(f"  1:1 pixel art: {outputs['one_to_one']}")
    print(f"  Scaled pixel art: {outputs['scaled']}")
    print(f"  Comparison: {outputs['comparison']}")


if __name__ == "__main__":
    main()
